swagger: '2.0'
info:
  version: '0.0.1'
  title: 'SEAL eMRTD IS ms'
  description: 'SEAL eMRTD Identity Source microservice'
#paths: {}
# basePath: /emrtd
paths:
  ####### IdentitySource #######

  /is/query:
    post:
      tags:
        - IdentitySource
      summary: Pass a data query request object to be handled by an identity module ms.
      description: Process a Data request
      consumes:
      - "application/x-www-form-urlencoded"
      parameters:
        - name: "msToken"
          in: formData   
          description: The security token for ms to ms calls
          required: true
          type: string
#        - name: "apRequest"
#          in: formData
#          description: The standard request object representing the request to be issued to the identity source
#          required: true
#          schema:
#            $ref: "#/definitions/attributeSet"
#        - name: "apMetadata"
#          in: query
#          description: The metadata object of the remote AP that must be queried
#          required: true
#          schema:
#            $ref: "#/definitions/entityMetadata"
#        - name: "authenticationSet"
#          in: query
#          description: A standard response object containing the attributes retreved from the user authentication on SEAL, if any (for now, just ignore).
#          required: false
#          schema:
#            $ref: "#/definitions/attributeSet"
      responses:
        200:
          description: "Request admitted"
        400:
          description: "Bad request"
        401:
          description: "Request not authorised"
  
  
  /is/load:
    post:
      tags:
        - IdentitySource
      summary: Passively provide trusted identity data from a trusted source to the identity source module. Can be used to implement a callback interface
      description: _
      consumes:
      - "application/x-www-form-urlencoded"
      parameters:
        - name: "msToken"
          in: "formData"
          description: The security token for ms to ms calls
          required: true
          type: string
#        - name: emrtdDataset
#          in: cookie
#          description: The data set to add
#          required: true
#          type: string #B64  $ref: '#/definitions/dataSet'
      responses:
        200:
          description: "Identity Dataset received"
        404:
          description: "Error receiving identity dataset"
          
definitions:

 # Descriptor Object for an Attribute Set (a data request or response)
  attributeSet:
    description: Object representing a generic request/response. Used for in-application transference of the security assertions or claims containing trusted user information (attribute values); also to set the list of attributes to be requested.
    type: object
    properties:
      id:
        description: Unique identifier of the set
        type: string
        example: "6c0f70a8-f32b-4535-b5f6-0d596c52813a"
      type:
        description: Kind of set
        type: string
        enum:
            - Request
            - Response
            - AuthResponse
        example: "Response"
      issuer:
        description: ID of the External Entity which issued the set
        type: string
        example: "https://esmo.uji.es/gw/saml/idp/metadata.xml"
      recipient:
        description: ID of the External Entity which the set is addressed to
        type: string
        example: "https://esmo.uji.es/gw/saml/sp/metadata.xml"
      inResponseTo:
        description: In response objects, the ID of the request which the set is responding to
        type: string
        example: "aaaa70a8-f32b-4535-b5f6-0d596cbbbbb"
      loa:
        description: Level of trust of the authentication related to the set, if it is a response for an eIDAS authentication request
        type: string
        example: "http://eidas.europa.eu/LoA/substantial"
      notBefore:
        description: Minimum validity date of the set
        type: string
        example: "2018-12-06T19:40:16Z"
      notAfter:
        description: Maximum validity date of the set
        type: string
        example: "2018-12-06T19:45:16Z"
      status:
        description: "To represent the tatus of the set (ok, error, etc.)."
        $ref: '#/definitions/attributeSetStatus'
      attributes:
        description: The list of the attributes or claims related to the user, contained on the set
        type: array
        items:
            $ref: '#/definitions/attributeType'
      properties:
        description: Dictionary of additional fields of data related to the attributes in the set(strings only), specific for a certain entity type or protocol. List of useful metadata related to the attributes and any specific information that came with the remote SP/RP request (or was filled in with metadata stored presets for said SP/RP) and might be of need for some implementation of the local SP to issue the authentication request.
        type: object
        #Indicates free-form object
        additionalProperties:
            type: string
     
  # Descriptor Object for an External Entity (data source, authsource)
  entityMetadata:
    description: Information about the an external entity
    type: object
    required: [entityId]
    properties:
      entityId:
        description: Unique identifier of the entity, usually a metadata url
        type: string
        example: "https://esmo.uji.es/gw/saml/idp/metadata.xml"
      defaultDisplayName:
        description: Name to be displayed on UI, in the default language/encoding
        type: string
        example: "UJI Identity Provider"
      displayNames:
        description: list of alternative display names, by language or encoding
        type: object
        additionalProperties:
            type: string
        example: {"ES" : "UJI Proveedor de Identidad","EN" : "UJI Identity Provider"}
      logo:
        description: B64 string with an image binary to be displayed at UI
        type: string
        example: "AWDGRsFbFDEfFGTNNJKKYGFVFfDDSSSDCCC=="
      location:
        description: unspecified list of information items about the physical or political location of the entity, to facilitate discovery
        type: array
        items:
          type: string
      protocol:
        description: Which protocol does this entity support (SAML, OIDC, etc.)
        type: string
      microservice:
        description: list of identifiers of microservice able to handle this external entity
        type: array
        items:
          type: string
      claims:
        description: list of attributes supported/requested by default by this entity
        type: array
        items:
          type: string
        example: ["displayName","surname","dateOfBirth","eduPersonAffiliation"]
      endpoints:
        description: List of service endpoints, where this Entity will accept requests/responses.
        type: array
        items:
          $ref: '#/definitions/endpointType'
      securityKeys:
        description: List of keys held by this entity
        type: array
        items:
          $ref: '#/definitions/securityKeyType'
      encryptResponses:
        description: whether this entity will issue/expect encrypted responses
        type: boolean
        example: false
      supportedEncryptionAlg:
        description: list of supported encryption algorithms
        type: array
        items:
          type: string
        example: ["AES256","AES512"]
      signResponses:
        description: whether this entity will issue/expect signed responses
        type: boolean
        example: true
      supportedSigningAlg:
        description: list of supported signing algorithms
        type: array
        items:
          type: string
        example: ["RSA-SHA256"]
      otherData:
        description: Dictionary of additional fields, specific for a certain entity type or protocol
        type: object
        additionalProperties: true   #Indicates free-form object
        example: ["attributeMappingToEIDAS" : {"displayName" : "CurrentGivenName", "surname" : "CurrentFamilyName"}]
  entityMetadataList:
     type: array
     items: 
       $ref: '#/definitions/entityMetadata'
  
  endpointType:
    description: Endpoint descriptor, where requests can be made or responses sent.
    type: object
    properties:
      type:
        description: String identifying the kind of endpoint (depends on each protocol)
        type: string
        example: "SSOService"
      method: 
        description: String identifying the method to access the endpoint (depends on each protocol, i.e. HTTP-POST).
        type: string
        example: "HTTP-POST"
      url:
        description: Access url of the endpoint 
        type: string
        example: "https://esmo.uji.es/gw/saml/idp/SSOService.php"
  securityKeyType:
    description: Descriptor of a key or certificate.
    type: object
    properties:
      keyType:
        description: String identifying the kind of key
        type: string
        example: "RSAPublicKey"
      usage: 
        description: To which use is this key intended.
        type: string
        enum:
            - signing
            - encryption
        example: "signing"
      key:
        description: B64 string representing the key binary 
        type: string
        example: "MDAACaFgw...xFgy="
  attributeSetStatus:
    type: object
    properties:
      code:
        description: main standard status code from a closed list.
        type: string
        enum:
            - OK
            - ERROR
      subcode:
        description: free text field to represent status codes, open for specific applications or fluxes.
        type: string
      message:
        description: a free text string to provide human-readable status-error information
        type: string
  attributeType:
    description: Contents of an attribute item.
    type: object
    properties:
      name:
        description: Unique class identifier of the attribute
        type: string
        example: "http://eidas.europa.eu/attributes/naturalperson/CurrentGivenName"
      friendlyName:
        description: Class identifier of the attribute (short version, might have collisions)
        type: string
        example: "CurrentGivenName"
      encoding:
        description: String identifying the encoding method:"UTF-8" , "BASE64", etc.
        type: string
        example: "plain"
      language:
        description: String identifying the language code of the value contents
        type: string
        example: "ES_es"
      isMandatory:
        description: To mark the mandatoriness of the attribute.
        type: boolean
        example: true
      values:
        description: List of values for the attribute
        type: array
        items:
          type: string
        example: ["JOHN"]


  attributeTypeList:
      type: array
      items: 
        $ref: '#/definitions/attributeType'
        
  dataSet:
    description: Object representing a generic identity data set, retrieved from some source and stored on a user store.
    type: object
    properties:
      id:
        description: Unique identifier of the set
        type: string
        example: "6c0f70a8-f32b-4535-b5f6-0d596c52813a"
      type:
        description: To define different kinds of datasets, to establish classifications
        type: string
      categories:
        description: To define multiple classes where the data set can be grouped.
        type: array
        items:
          type: string
      issuerId:
        description: Name of the attribute that is the ID of the entity that issued the data set, a kind of pointer to the property ID.
        type: string
      subjectId:
        description: Name of the attribute that is the ID of the data owner, a kind of pointer to the attribute ID.
        type: string
      loa:
        description: Level of assurance of the authenticity of the data/authentication
        type: string
      issued:
        description: Date when the data set was retrieved from its source
        type: string
        example: "2018-12-06T19:40:16Z"
      expiration:
        description: Maximum validity date of the set (empty means permanent)
        type: string
        example: "2018-12-06T19:45:16Z"
      attributes:
        description: The list of the identity attributes or claims contained on the set
        type: array
        items:
            $ref: '#/definitions/attributeType'
      properties:
        description: Dictionary of additional fields of data related to the attributes in the set(strings only) for any specific purpose.
        type: object
        #Indicates free-form object
        additionalProperties:
            type: string       
